export const PHASES = [
  {
    id: 0,
    title: "硬件与基础代码",
    subtitle: "Reset / CRT0 / 基础时钟",
    color: "#d97706",
  },
  {
    id: 1,
    title: "EcuM 启动前期",
    subtitle: "InitZero / InitOne / StartOS 准备",
    color: "#2563eb",
  },
  {
    id: 2,
    title: "操作系统启动",
    subtitle: "StartOS / StartupTask",
    color: "#7c3aed",
  },
  {
    id: 3,
    title: "EcuM 启动后期",
    subtitle: "StartupTwo / SchM / BswM 接管",
    color: "#0f766e",
  },
  {
    id: 4,
    title: "BSW 基础初始化",
    subtitle: "驱动 / 存储 / 诊断 / 通信栈",
    color: "#059669",
  },
  {
    id: 5,
    title: "RTE 启动与模式切换",
    subtitle: "NvM 完成 / ComM / CanSM / Rte_StartTiming",
    color: "#9333ea",
  },
  {
    id: 6,
    title: "运行模式",
    subtitle: "周期任务 / 信号 / 通信 / 诊断",
    color: "#dc2626",
  },
];

export const MODULES = [
  {
    id: "power",
    name: "Power & Reset",
    description: "上电、复位和基础供电稳定条件。",
    layer: "hardware",
    apis: ["POR", "WarmReset"],
  },
  {
    id: "mcu",
    name: "Mcu",
    description: "MCU 时钟、PLL、复位原因和模式管理。",
    layer: "mcal",
    apis: [
      "Mcu_Init",
      "Mcu_InitClock",
      "Mcu_DistributePllClock",
      "Mcu_GetResetReason",
    ],
  },
  {
    id: "port",
    name: "Port",
    description: "引脚复用与方向初始化。",
    layer: "mcal",
    apis: ["Port_Init"],
  },
  {
    id: "dio",
    name: "Dio",
    description: "数字 IO 抽象访问。",
    layer: "mcal",
    apis: ["Dio_ReadChannel", "Dio_WriteChannel"],
  },
  {
    id: "adc",
    name: "Adc",
    description: "模拟采样入口，驱动传感器采集。",
    layer: "mcal",
    apis: ["Adc_Init", "Adc_ReadGroup"],
  },
  {
    id: "pwm",
    name: "Pwm",
    description: "执行器 PWM 输出。",
    layer: "mcal",
    apis: ["Pwm_Init", "Pwm_SetDutyCycle"],
  },
  {
    id: "gpt",
    name: "Gpt",
    description: "通用定时器，为节拍和诊断提供时基。",
    layer: "mcal",
    apis: ["Gpt_Init", "Gpt_StartTimer"],
  },
  {
    id: "spi",
    name: "Spi",
    description: "板级外设串行通信。",
    layer: "mcal",
    apis: ["Spi_Init", "Spi_SyncTransmit"],
  },
  {
    id: "candrv",
    name: "Can Driver",
    description: "CAN 控制器与收发器驱动。",
    layer: "mcal",
    apis: ["Can_Init", "Can_SetControllerMode", "Can_Write"],
  },
  {
    id: "wdg",
    name: "Wdg",
    description: "硬件看门狗驱动。",
    layer: "mcal",
    apis: ["Wdg_Init", "Wdg_SetMode", "Wdg_SetTriggerCondition"],
  },
  {
    id: "fls",
    name: "Fls",
    description: "Flash 读写底层驱动。",
    layer: "mcal",
    apis: ["Fls_Init", "Fls_Read"],
  },
  {
    id: "canif",
    name: "CanIf",
    description: "CAN 接口，上接 PduR / Com，下接 CanDrv。",
    layer: "abstraction",
    apis: ["CanIf_Init", "CanIf_Transmit", "CanIf_SetControllerMode"],
  },
  {
    id: "cantp",
    name: "CanTp",
    description: "ISO-TP 分段重组。",
    layer: "service",
    apis: ["CanTp_Init"],
  },
  {
    id: "memif",
    name: "MemIf",
    description: "非易失存储抽象统一接口。",
    layer: "abstraction",
    apis: ["MemIf_GetStatus", "MemIf_GetJobResult", "MemIf_Read"],
  },
  {
    id: "fee",
    name: "Fee",
    description: "Flash EEPROM 模拟层。",
    layer: "abstraction",
    apis: ["Fee_Init", "Fee_Read"],
  },
  {
    id: "iohwab",
    name: "IoHwAb",
    description: "ECU 抽象层，对上隐藏具体硬件通道。",
    layer: "abstraction",
    apis: ["IoHwAb_Init", "IoHwAb_ReadSensor", "IoHwAb_WriteActuator"],
  },
  {
    id: "wdgif",
    name: "WdgIf",
    description: "看门狗统一接口。",
    layer: "abstraction",
    apis: ["WdgIf_SetMode", "WdgIf_SetTriggerCondition"],
  },
  {
    id: "ecum",
    name: "EcuM",
    description: "ECU 状态管理器，负责启动骨架与模式切换。",
    layer: "service",
    apis: ["EcuM_Init", "EcuM_StartupTwo"],
  },
  {
    id: "bswm",
    name: "BswM",
    description: "BSW 模式管理，按配置执行规则与动作。",
    layer: "service",
    apis: ["BswM_Init", "BswM_RequestMode"],
  },
  {
    id: "schm",
    name: "SchM",
    description: "BSW 调度协调和 MainFunction 节拍分发。",
    layer: "service",
    apis: ["SchM_Start", "SchM_Init", "SchM_StartTiming"],
  },
  {
    id: "os",
    name: "OS",
    description: "AUTOSAR OS，任务、调度和中断承载者。",
    layer: "service",
    apis: ["StartOS", "ActivateTask"],
  },
  {
    id: "comm",
    name: "ComM",
    description: "通信模式管理，区分目标请求与实际总线模式。",
    layer: "service",
    apis: ["ComM_Init", "ComM_RequestComMode", "ComM_BusSM_ModeIndication"],
  },
  {
    id: "com",
    name: "Com",
    description: "信号打包、解包与 I-PDU 管理。",
    layer: "service",
    apis: ["Com_Init", "Com_SendSignal"],
  },
  {
    id: "pdur",
    name: "PduR",
    description: "PDU 路由层。",
    layer: "service",
    apis: ["PduR_Init"],
  },
  {
    id: "cansm",
    name: "CanSM",
    description: "CAN 状态管理，异步推动控制器进入目标模式。",
    layer: "service",
    apis: ["CanSM_Init", "CanSM_RequestComMode"],
  },
  {
    id: "nm",
    name: "Nm",
    description: "网络管理。",
    layer: "service",
    apis: ["Nm_Init"],
  },
  {
    id: "dcm",
    name: "Dcm",
    description: "诊断通信管理。",
    layer: "service",
    apis: ["Dcm_Init"],
  },
  {
    id: "dem",
    name: "Dem",
    description: "诊断事件管理。",
    layer: "service",
    apis: ["Dem_Init", "Dem_ReportErrorStatus"],
  },
  {
    id: "nvm",
    name: "NvM",
    description: "非易失存储管理；ReadAll 为异步流程。",
    layer: "service",
    apis: ["NvM_Init", "NvM_ReadAll", "NvM_MainFunction"],
  },
  {
    id: "wdgm",
    name: "WdgM",
    description: "软件看门狗监控。",
    layer: "service",
    apis: ["WdgM_Init", "WdgM_CheckpointReached"],
  },
  {
    id: "det",
    name: "Det",
    description: "开发错误跟踪。",
    layer: "service",
    apis: ["Det_Init", "Det_ReportError"],
  },
  {
    id: "rte",
    name: "RTE",
    description: "运行时环境，连接 SWC 与 BSW。",
    layer: "rte",
    apis: ["Rte_Start", "Rte_Init_Startup", "Rte_StartTiming"],
  },
  {
    id: "sensor",
    name: "Sensor SWC",
    description: "采样与预处理示例 SWC。",
    layer: "app",
    apis: ["Swc_Sensor_1ms"],
  },
  {
    id: "controller",
    name: "Controller SWC",
    description: "控制算法示例 SWC。",
    layer: "app",
    apis: ["Swc_Control_5ms"],
  },
  {
    id: "actuator",
    name: "Actuator SWC",
    description: "执行器输出示例 SWC。",
    layer: "app",
    apis: ["Swc_Actuator_10ms"],
  },
  {
    id: "logger",
    name: "Logger SWC",
    description: "教学界面日志与诊断镜像示例。",
    layer: "app",
    apis: ["Swc_Logger_100ms"],
  },
  {
    id: "cdd",
    name: "CDD",
    description: "复杂驱动示例占位；它是跨层的项目集成代码，不是应用 SWC。",
    layer: "abstraction",
    apis: ["Board_PostOsHook"],
  },
];

export const SCENARIOS = [
  {
    id: "normal",
    label: "正常启动",
    description: "PLL 成功锁定，NvM 正常完成，CAN 网络最终进入 FULL_COM。",
  },
  {
    id: "pll-failure",
    label: "PLL 锁定失败",
    description: "启动在时钟分发阶段阻塞，系统不会越过 StartOS。",
  },
  {
    id: "nvm-slow",
    label: "NvM 读取偏慢",
    description: "NvM_ReadAll 只是发起请求，实际完成要靠后续 MainFunction 轮询。",
  },
  {
    id: "nvm-crc",
    label: "NvM CRC 失败",
    description: "示例策略：块校验失败时回退 ROM 默认值并带告警继续启动。",
  },
  {
    id: "can-bus-off",
    label: "CAN Bus-Off",
    description: "系统可进入 RUN，但实际通信模式不上线，不产生成功 CAN 帧。",
  },
];

export const TASKS = [
  {
    id: "task-1ms",
    name: "Task_1ms",
    period: 1,
    duration: 0.125,
    color: "#2563eb",
  },
  {
    id: "task-5ms",
    name: "Task_5ms",
    period: 5,
    duration: 0.375,
    color: "#059669",
  },
  {
    id: "task-10ms",
    name: "Task_10ms",
    period: 10,
    duration: 0.625,
    color: "#d97706",
  },
  {
    id: "task-100ms",
    name: "Task_100ms",
    period: 100,
    duration: 1.125,
    color: "#7c3aed",
  },
];

export const STEPS = [
  {
    id: 1,
    phase: 0,
    title: "上电复位与硬件稳定",
    description: "电源稳定后 CPU 落入复位向量。",
    api: "POR / Reset_Handler",
    caller: "power",
    target: "mcu",
    modules: ["power", "mcu"],
    duration: 2,
    explanation: "教学示例从上电复位开始，不覆盖 BootROM 厂商私有细节。",
    code: "Reset_Handler();",
  },
  {
    id: 2,
    phase: 0,
    title: "CRT0 初始化栈与数据段",
    description: "建立栈指针，拷贝 .data，清零 .bss。",
    api: "crt0_init",
    caller: "mcu",
    target: "mcu",
    modules: ["mcu"],
    duration: 3,
    explanation: "这是 C 运行环境准备阶段，通常早于任何 AUTOSAR 模块。",
    code: "crt0_init();",
  },
  {
    id: 3,
    phase: 0,
    title: "最低限度板级时钟与向量表准备",
    description: "建立可执行环境，尚未进入项目时钟树。",
    api: "board_early_init",
    caller: "mcu",
    target: "mcu",
    modules: ["mcu"],
    duration: 2,
    explanation: "只准备后续初始化所需的最小硬件环境。",
    code: "Board_EarlyInit();",
  },
  {
    id: 4,
    phase: 0,
    title: "进入 main 并建立最小错误处理",
    description: "从启动代码进入应用入口，建立最小可诊断环境。",
    api: "main",
    caller: "mcu",
    target: "mcu",
    modules: ["mcu"],
    duration: 3,
    explanation: "这一阶段还不是 AUTOSAR EcuM 控制的 MCU 初始化，只是进入 C 程序主线。",
    code: "main();",
  },
  {
    id: 5,
    phase: 0,
    title: "板级最小安全态建立",
    description: "拉起上电必须的安全 GPIO、电源和故障兜底路径。",
    api: "Board_PreEcuMInit",
    caller: "mcu",
    target: "power",
    modules: ["power", "mcu", "port"],
    duration: 4,
    explanation: "这里只保留早于 EcuM 的板级最小准备，不混入配置化 MCU 驱动初始化。",
    code: "Board_PreEcuMInit();",
  },
  {
    id: 6,
    phase: 0,
    title: "跳转到 AUTOSAR 启动入口",
    description: "基础环境就绪，准备进入 EcuM 接管阶段。",
    api: "Autosar_MainEntry",
    caller: "mcu",
    target: "ecum",
    modules: ["mcu"],
    duration: 2,
    explanation: "到这一步仍未执行 EcuM_Init，界面不会提前把 EcuM 标成已启动。",
    code: "Autosar_MainEntry();",
  },
  {
    id: 7,
    phase: 1,
    title: "EcuM_Init 进入 STARTUP I",
    description: "EcuM 状态机接管 ECU 启动骨架。",
    api: "EcuM_Init",
    caller: "mcu",
    target: "ecum",
    modules: ["ecum"],
    duration: 4,
    explanation: "从这里开始进入 EcuM STARTUP I 教学阶段。",
    code: "EcuM_Init();",
  },
  {
    id: 8,
    phase: 1,
    title: "DriverInitZero 最早期驱动准备",
    description: "只做不依赖 Post-Build 配置的最小化驱动初始化。",
    api: "EcuM_AL_DriverInitZero",
    caller: "ecum",
    target: "det",
    modules: ["ecum", "det"],
    duration: 3,
    explanation: "依据规范骨架，InitZero 发生在确定 Post-Build 配置之前。",
    code: "EcuM_AL_DriverInitZero();",
  },
  {
    id: 9,
    phase: 1,
    title: "DeterminePbConfiguration 选择配置集",
    description: "判定本次启动采用的 Post-Build 配置。",
    api: "EcuM_DeterminePbConfiguration",
    caller: "ecum",
    target: "ecum",
    modules: ["ecum"],
    duration: 4,
    explanation: "教学页面把配置选择单独画出，强调它先于 InitOne。",
    code: "cfg = EcuM_DeterminePbConfiguration();",
  },
  {
    id: 10,
    phase: 1,
    title: "一致性校验与启动合法性检查",
    description: "对配置与启动条件做一致性检查。",
    api: "EcuM_ValidatePbConfiguration",
    caller: "ecum",
    target: "det",
    modules: ["ecum", "det"],
    duration: 3,
    explanation: "校验失败在规范里不能继续 StartOS，本示例正常场景默认通过。",
    code: "EcuM_ValidatePbConfiguration(cfg);",
  },
  {
    id: 11,
    phase: 1,
    title: "DriverInitOne 与 Mcu_Init",
    description: "在配置集确定后，执行 DriverInitOne 并装载 MCU 配置。",
    api: "EcuM_AL_DriverInitOne / Mcu_Init",
    caller: "ecum",
    target: "mcu",
    modules: ["ecum", "mcu", "wdg"],
    duration: 5,
    explanation: "这里仍是 STARTUP I，但现在才开始进入依赖配置的 MCU 驱动初始化。",
    code: "EcuM_AL_DriverInitOne(); Mcu_Init(&Mcu_Config);",
  },
  {
    id: 12,
    phase: 1,
    title: "Mcu_InitClock 并轮询 Mcu_GetPllStatus",
    description: "请求项目时钟后轮询 PLL 状态，未锁定时不能分发主时钟。",
    api: "Mcu_InitClock / Mcu_GetPllStatus",
    caller: "ecum",
    target: "mcu",
    modules: ["ecum", "mcu"],
    duration: 4,
    explanation: "PLL 失败场景在这里阻塞，遵循“先确认 locked，再 Distribute”的教学约束。",
    code: "Mcu_InitClock(MCU_CLOCK_CFG_0); while (Mcu_GetPllStatus() != MCU_PLL_LOCKED) { }",
  },
  {
    id: 13,
    phase: 1,
    title: "分发 PLL 时钟、读取复位原因并准备 StartOS",
    description: "主时钟就绪后切换频点，读取复位原因并完成 pre-OS 收尾。",
    api: "Mcu_DistributePllClock / Mcu_GetResetReason / EcuM_PrepareStartOS",
    caller: "ecum",
    target: "mcu",
    modules: ["ecum", "mcu"],
    duration: 4,
    explanation: "这里才把控制权推向 StartOS，仍保持 pre-OS 不依赖运行中的 OS 服务。",
    code: "Mcu_DistributePllClock(); resetReason = Mcu_GetResetReason(); EcuM_PrepareStartOS();",
  },
  {
    id: 14,
    phase: 2,
    title: "StartOS 启动 AUTOSAR OS",
    description: "调度器开始工作，StartupTask 可被激活。",
    api: "StartOS",
    caller: "ecum",
    target: "os",
    modules: ["os"],
    duration: 4,
    explanation: "StartOS 之后才能安全使用依赖 OS 的 Category II 中断与任务调度。",
    code: "StartOS(OSDEFAULTAPPMODE);",
  },
  {
    id: 15,
    phase: 2,
    title: "自动启动任务进入 StartupTask",
    description: "OS 自动启动的任务接过后续启动流程。",
    api: "OS autostart: StartupTask",
    caller: "os",
    target: "ecum",
    modules: ["os", "ecum"],
    duration: 2,
    explanation: "Classic Flexible 常见做法是由 StartupTask 调用后续 StartupTwo。",
    code: "/* OsTask AUTOSTART = TRUE; */",
  },
  {
    id: 16,
    phase: 3,
    title: "StartupTask 调用 EcuM_StartupTwo",
    description: "EcuM 进入 STARTUP II。",
    api: "EcuM_StartupTwo",
    caller: "ecum",
    target: "ecum",
    modules: ["ecum"],
    duration: 4,
    explanation: "从这一步起进入 post-OS 侧的启动阶段。",
    code: "EcuM_StartupTwo();",
  },
  {
    id: 17,
    phase: 3,
    title: "SchM_Start 建立 BSW 调度入口",
    description: "规范骨架中的 post-OS 首个调度管理动作。",
    api: "SchM_Start",
    caller: "ecum",
    target: "schm",
    modules: ["ecum", "schm"],
    duration: 2,
    explanation: "这里保持 SchM_Start 在 BswM_Init 与 SchM_Init 之前。",
    code: "SchM_Start();",
  },
  {
    id: 18,
    phase: 3,
    title: "BswM_Init 启动模式规则机",
    description: "BSW 模式管理开始接管配置化规则。",
    api: "BswM_Init",
    caller: "ecum",
    target: "bswm",
    modules: ["ecum", "bswm"],
    duration: 3,
    explanation: "现代 Flexible 更适合把后续细化逻辑放到 BswM 规则中表达。",
    code: "BswM_Init();",
  },
  {
    id: 19,
    phase: 3,
    title: "SchM_Init 准备 MainFunction 路由",
    description: "建立调度映射，但此时还未开始周期触发。",
    api: "SchM_Init",
    caller: "ecum",
    target: "schm",
    modules: ["ecum", "schm"],
    duration: 2,
    explanation: "按规范骨架，SchM_Init 位于 BswM_Init 之后、SchM_StartTiming 之前。",
    code: "SchM_Init();",
  },
  {
    id: 20,
    phase: 3,
    title: "SchM_StartTiming 开启 BSW 时基",
    description: "允许 BSW MainFunction 进入周期调度。",
    api: "SchM_StartTiming",
    caller: "ecum",
    target: "schm",
    modules: ["ecum", "schm", "os"],
    duration: 2,
    explanation: "教学模型在这里开始允许异步型服务进入轮询推进。",
    code: "SchM_StartTiming();",
  },
  {
    id: 21,
    phase: 3,
    title: "项目板级 post-OS hook 返回",
    description: "示例化展示项目自定义的板级 post-OS 钩子。",
    api: "Board_PostOsHook",
    caller: "ecum",
    target: "cdd",
    modules: ["ecum", "cdd"],
    duration: 2,
    explanation: "这一步是教学示例，不是所有 AUTOSAR 项目都必须存在。",
    code: "Board_PostOsHook();",
  },
  {
    id: 22,
    phase: 3,
    title: "BswM 进入 STARTUP 规则集",
    description: "规则机开始决定哪些 BSW 初始化可继续推进。",
    api: "BswM_RequestMode(STARTUP)",
    caller: "ecum",
    target: "bswm",
    modules: ["ecum", "bswm", "comm"],
    duration: 2,
    explanation: "这里明确区分：教学规则集是示例配置，不是规范强制序列。",
    code: "BswM_RequestMode(BSWM_STARTUP);",
  },
  {
    id: 23,
    phase: 3,
    title: "StartupTask 完成并把后续推进交给 BSW",
    description: "启动主线从 EcuM 过渡到 BSW MainFunction 驱动。",
    api: "StartupTask_Return",
    caller: "ecum",
    target: "bswm",
    modules: ["ecum", "bswm"],
    duration: 2,
    explanation: "后续很多服务以异步 MainFunction 形式推进。",
    code: "TerminateTask();",
  },
  {
    id: 24,
    phase: 4,
    title: "项目示例驱动组初始化",
    description: "初始化 Port / Adc / Pwm / Gpt / Spi / Can / Wdg / Fls / IoHwAb，并标注 Dio / WdgIf 为接口层就绪。",
    api: "Project_DriverInitGroup",
    caller: "bswm",
    target: "iohwab",
    modules: [
      "bswm",
      "port",
      "dio",
      "adc",
      "pwm",
      "gpt",
      "spi",
      "candrv",
      "wdg",
      "fls",
      "iohwab",
    ],
    duration: 6,
    explanation: "后期驱动组顺序是示例化工程配置，界面会明确标注并非 AUTOSAR 强制固定顺序。",
    code: "Project_DriverInitGroup();",
  },
  {
    id: 25,
    phase: 4,
    title: "MemIf / Fee / NvM 初始化",
    description: "建立非易失存储服务栈。",
    api: "NvM_Init",
    caller: "bswm",
    target: "nvm",
    modules: ["bswm", "memif", "fee", "nvm", "fls"],
    duration: 4,
    explanation: "MemIf 本身主要提供统一读写状态接口，示例中真正显式初始化的是 Fee / NvM。",
    code: "Fee_Init(); NvM_Init();",
  },
  {
    id: 26,
    phase: 4,
    title: "NvM_ReadAll 异步请求发起",
    description: "只设置请求为 pending，不代表数据已经就绪。",
    api: "NvM_ReadAll",
    caller: "bswm",
    target: "nvm",
    modules: ["bswm", "nvm", "fee"],
    duration: 2,
    explanation: "这是教学重点：ReadAll 是异步调用，真正完成要靠后续轮询或回调推进。",
    code: "NvM_ReadAll();",
  },
  {
    id: 27,
    phase: 4,
    title: "通信栈基础模块初始化",
    description: "初始化 CanIf / CanTp / PduR / Com / ComM / Nm / CanSM。",
    api: "CommunicationStack_Init",
    caller: "bswm",
    target: "comm",
    modules: ["bswm", "canif", "cantp", "pdur", "com", "comm", "cansm", "nm"],
    duration: 5,
    explanation: "这里只是模块 init，不等于通信网络已经进入实际 FULL_COM。",
    code: "CommunicationStack_Init();",
  },
  {
    id: 28,
    phase: 4,
    title: "诊断与监控模块初始化",
    description: "初始化 Dcm / Dem / Det / WdgM / WdgIf / Logger。",
    api: "DiagAndMonitor_Init",
    caller: "bswm",
    target: "dem",
    modules: ["bswm", "dcm", "dem", "det", "wdgm", "wdgif", "iohwab", "logger"],
    duration: 4,
    explanation: "这些模块的组合与先后仍属于示例配置，不应被解读为规范硬编码顺序。",
    code: "DiagAndMonitor_Init();",
  },
  {
    id: 29,
    phase: 4,
    title: "NvM_MainFunction 轮询块恢复状态",
    description: "读取请求仍可能处于 pending。",
    api: "NvM_MainFunction",
    caller: "schm",
    target: "nvm",
    modules: ["schm", "nvm"],
    duration: 3,
    explanation: "normal 场景很快完成，nvm-slow 场景会在这里继续等待。",
    code: "NvM_MainFunction();",
  },
  {
    id: 30,
    phase: 4,
    title: "BswM 评估通信允许条件",
    description: "示例项目仍保持 CommunicationAllowed=FALSE。",
    api: "BswM_EvaluateCommunicationRules",
    caller: "bswm",
    target: "comm",
    modules: ["bswm", "comm", "cansm"],
    duration: 2,
    explanation: "ComM 初始允许标志为 FALSE；是否放开由配置动作决定。",
    code: "BswM_EvaluateCommunicationRules();",
  },
  {
    id: 31,
    phase: 4,
    title: "NvM 多块恢复结果通知 BswM",
    description: "NVRAM 相关数据到位，或在 CRC 失败时装载 ROM 默认值并上报模式结果。",
    api: "BswM_NvM_CurrentJobMode",
    caller: "nvm",
    target: "bswm",
    modules: ["nvm", "bswm"],
    duration: 4,
    explanation: "CRC 失败继续启动是本示例策略，不是 AUTOSAR 对所有项目的统一要求。",
    code: "BswM_NvM_CurrentJobMode(NVM_READ_ALL, NVM_REQ_OK);",
  },
  {
    id: 32,
    phase: 5,
    title: "BswM 放开 CommunicationAllowed 并请求 FULL_COM",
    description: "先放开通信许可，再由 ComM 提交目标模式请求。",
    api: "ComM_CommunicationAllowed / ComM_RequestComMode",
    caller: "bswm",
    target: "comm",
    modules: ["bswm", "comm", "cansm"],
    duration: 2,
    explanation: "教学界面把通信许可、requested 与 actual 明确拆开，避免把请求误当结果。",
    code: "ComM_CommunicationAllowed(NETWORK_0, TRUE); ComM_RequestComMode(USER_APP, COMM_FULL_COMMUNICATION);",
  },
  {
    id: 33,
    phase: 5,
    title: "CanSM 异步接受请求并启动控制器",
    description: "CanSM 接收 FULL_COM 请求，开始推动控制器与收发器切换模式。",
    api: "CanSM_RequestComMode(FULL_COM)",
    caller: "comm",
    target: "cansm",
    modules: ["comm", "cansm", "candrv", "canif"],
    duration: 4,
    explanation: "E_OK 只表示请求被接受，不表示总线已经上线。",
    code: "CanSM_RequestComMode(NETWORK_0, COMM_FULL_COMMUNICATION);",
  },
  {
    id: 34,
    phase: 5,
    title: "BusSM 模式反馈 actual 通信状态",
    description: "ComM 根据 BusSM 反馈更新 actual 模式。",
    api: "ComM_BusSM_ModeIndication",
    caller: "cansm",
    target: "comm",
    modules: ["cansm", "comm", "canif"],
    duration: 3,
    explanation: "normal 场景 actual 变成 FULL_COM；bus-off 场景保持离线并报警。",
    code: "ComM_BusSM_ModeIndication(NETWORK_0, mode);",
  },
  {
    id: 35,
    phase: 5,
    title: "Rte_Start 建立 RTE 栈框架",
    description: "RTE 主体启动，但周期 runnable 还未放开。",
    api: "Rte_Start",
    caller: "bswm",
    target: "rte",
    modules: ["bswm", "rte"],
    duration: 2,
    explanation: "本教学配置选择在 NvM 就绪和通信反馈之后再启动 RTE，这是保守门槛，不代表所有 AUTOSAR 项目都必须如此。",
    code: "Rte_Start();",
  },
  {
    id: 36,
    phase: 5,
    title: "Rte_Init_Startup 初始化示例批次",
    description: "执行 Startup 容器里的初始化 runnable。",
    api: "Rte_Init_Startup",
    caller: "rte",
    target: "rte",
    modules: ["rte"],
    duration: 3,
    explanation: "Startup 是示例批次名，用来演示 RTE 在 Start 与 StartTiming 之间的初始化窗口。",
    code: "Rte_Init_Startup();",
  },
  {
    id: 37,
    phase: 5,
    title: "Rte_StartTiming 并切换项目 APP_RUN 门控",
    description: "放开 TimingEvent，示例项目同时切到 APP_RUN。",
    api: "Rte_StartTiming",
    caller: "bswm",
    target: "rte",
    modules: ["bswm", "rte", "schm", "sensor", "controller", "actuator", "logger"],
    duration: 3,
    explanation: "把应用任务放在网络上线之后是项目门控示例，不是 AUTOSAR 对所有 SWC 的普遍前提。",
    code: "Rte_StartTiming();",
  },
  {
    id: 38,
    phase: 6,
    title: "1ms 任务首次采样传感器",
    description: "传感器 runnable 首次执行，更新原始采样值。",
    api: "Swc_Sensor_1ms",
    caller: "rte",
    target: "sensor",
    modules: ["rte", "sensor", "adc"],
    duration: 1,
    explanation: "运行期任务从这里开始真正产生信号。",
    code: "Swc_Sensor_1ms();",
  },
  {
    id: 39,
    phase: 6,
    title: "5ms 控制任务计算执行量",
    description: "控制 SWC 根据滤波后的采样值计算执行器目标。",
    api: "Swc_Control_5ms",
    caller: "rte",
    target: "controller",
    modules: ["rte", "controller"],
    duration: 1,
    explanation: "教学示例给出最小控制闭环，便于观察 RTE 周期调度效果。",
    code: "Swc_Control_5ms();",
  },
  {
    id: 40,
    phase: 6,
    title: "10ms 通信任务发送心跳",
    description: "Com 打包心跳，若网络已实际上线则经 CanIf 发出。",
    api: "Com_SendSignal / CanIf_Transmit",
    caller: "rte",
    target: "com",
    modules: ["rte", "actuator", "com", "canif"],
    duration: 1,
    explanation: "bus-off 场景在这里不会凭空出现成功 CAN 帧。",
    code: "Com_SendSignal(SIG_HEARTBEAT, &heartbeat);",
  },
  {
    id: 41,
    phase: 6,
    title: "100ms 后台诊断与日志任务",
    description: "后台任务刷新诊断快照与教学日志。",
    api: "Swc_Logger_100ms",
    caller: "rte",
    target: "logger",
    modules: ["rte", "logger", "dem", "dcm", "wdgm"],
    duration: 1,
    explanation: "该任务让页面持续可见地反映 RUN 阶段状态。",
    code: "Swc_Logger_100ms();",
  },
  {
    id: 42,
    phase: 6,
    title: "稳定进入 RUN 模式",
    description: "EcuM 教学状态进入 RUN，后续只剩周期调度与故障演示。",
    api: "RUN",
    caller: "ecum",
    target: "bswm",
    modules: ["ecum", "bswm", "os", "rte", "logger"],
    duration: 2,
    explanation: "RUN 之后页面改用虚拟单核调度推进，不再继续新增启动步骤。",
    code: "/* BswM action: application mode = RUN */",
  },
];
